namespace AudioAnalyzer.Domain;

/// <summary>
/// A named snapshot of a TextLayers configuration (<see cref="TextLayersLimits.MaxLayerCount"/> layers + PaletteId).
/// Name is autogenerated on creation but can be modified by the user.
/// </summary>
public class Preset
{
    /// <summary>Stable identifier for this preset (e.g. Guid). Used to track active preset.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>Display name. Autogenerated on creation (e.g. "Preset 1"), user-editable.</summary>
    public string Name { get; set; } = "Preset 1";

    /// <summary>Full layer configuration (<see cref="TextLayersLimits.MaxLayerCount"/> layers + PaletteId). Deep-copied when switching presets.</summary>
    public TextLayersVisualizerSettings Config { get; set; } = new();
}
